title: Andy Cho
tagline: I make things
author:
  name: Andy Cho
  email: contact@andycho.ca
  github: acromace
  twitter: acromace

production_url: http://acromace.com

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "project"
